export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR";

export const REQUEST_TOASTERS = "REQUEST_TOASTERS";
export const GET_TOASTERS_SUCCESS = "GET_TOASTERS_SUCCESS";
export const GET_TOASTERS_ERROR = "GET_TOASTERS_ERROR";

export const TOASTER_PRODUCTS_REQUEST = "TOASTER_PRODUCTS_REQUEST";
export const TOASTER_PRODUCTS_SUCCESS = "TOASTER_PRODUCTS_SUCCESS";
export const TOASTER_PRODUCTS_ERROR = "TOASTER_PRODUCTS_ERROR";

export const LOGOUT = "LOGOUT";